const $=s=>document.querySelector(s),K='arina-psy-trainer-v1';let bank=[],p=JSON.parse(localStorage.getItem(K)||'{"seen":[],"correct":0,"wrong":0,"errors":[],"history":[]}'),sess=null;const save=()=>localStorage.setItem(K,JSON.stringify(p)),esc=x=>String(x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function nav(a){$('#nav').innerHTML=[['home','Главная'],['full','Полный круг'],['errors','Круг ошибок'],['exam','Экзамен'],['materials','Материалы'],['progress','Прогресс']].map(x=>'<button class="'+(a==x[0]?'active':'')+'" data-t="'+x[0]+'">'+x[1]+'</button>').join('');$('#nav').onclick=e=>{if(e.target.dataset.t)render(e.target.dataset.t)}}
function render(t){nav(t);({home,full,errors,exam,materials,progress:progressView}[t]||home)()}
function home(){$('#app').innerHTML='<article class=card><h2>Спокойная подготовка</h2><p>120 авторских вопросов по медицинской психологии.</p><div class=stats><div class=stat><b>'+bank.length+'</b>вопросов</div><div class=stat><b>'+p.errors.length+'</b>активных ошибок</div><div class=stat><b>'+p.correct+'</b>правильных</div></div></article><div class=grid><button class=mode data-go=full>Полный круг</button><button class=mode data-go=errors>Круг ошибок</button><button class=mode data-go=exam>Экзамен</button></div>';$('#app').onclick=e=>{let b=e.target.closest('[data-go]');if(b)render(b.dataset.go)}}
function start(m,l){sess={mode:m,list:l.slice().sort(()=>Math.random()-.5),i:0,answered:false};show()};function full(){start('full',bank)};function errors(){start('errors',bank.filter(q=>p.errors.includes(q.id)))};function exam(){start('exam',bank.slice().sort(()=>Math.random()-.5).slice(0,20))}
function show(){if(!sess.list.length){$('#app').innerHTML='<article class=card><h2>Ошибок нет</h2><button id=home>На главную</button></article>';$('#home').onclick=()=>render('home');return}if(sess.i>=sess.list.length){$('#app').innerHTML='<article class=card><h2>Круг завершён</h2><p>Активных ошибок: '+p.errors.length+'</p><button id=home>На главную</button></article>';$('#home').onclick=()=>render('home');return}let q=sess.list[sess.i];$('#app').innerHTML='<article class=card><div class=row><span class=topic>'+esc(q.topic)+'</span><span>'+ (sess.i+1)+' / '+sess.list.length+'</span></div><p class=question>'+esc(q.question)+'</p><div class=answers>'+q.options.map((o,i)=>'<button class=answer data-a='+i+'>'+('АБВГ'[i])+'. '+esc(o)+'</button>').join('')+'</div></article>';$('#app').onclick=e=>{let b=e.target.closest('[data-a]');if(b&&!sess.answered)answer(+b.dataset.a)}}
function answer(c){sess.answered=true;let q=sess.list[sess.i],ok=c===q.answer;if(!p.seen.includes(q.id))p.seen.push(q.id);if(ok){p.correct++;p.errors=p.errors.filter(x=>x!==q.id)}else{p.wrong++;if(!p.errors.includes(q.id))p.errors.push(q.id)}save();document.querySelectorAll('.answer').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===c&&!ok)b.classList.add('wrong')});let r=document.createElement('article');r.className='card result';r.innerHTML='<h3>'+(ok?'Верно — вопрос удалён из активных ошибок.':'Пока ошибка — вопрос добавлен в активный круг.')+'</h3><p>'+esc(q.explanation)+'</p><p><b>Почему другие не подходят:</b> '+esc(q.wrong)+'</p><p><b>Ассоциация:</b> '+esc(q.mnemonic)+'</p><button id=next>Продолжить</button>';$('#app').append(r);$('#next').onclick=()=>{if(sess.mode==='errors'&&ok)sess.list.splice(sess.i,1);else sess.i++;sess.answered=false;show()}}
function materials(){$('#app').innerHTML='<article class=card><h2>Материалы</h2><p>Нейропсихология · патопсихология · психосоматика · семья · соматоформные расстройства · клиника · психотерапия · этика.</p></article>'};function progressView(){$('#app').innerHTML='<article class=card><h2>Прогресс</h2><p>Пройдено: '+p.seen.length+' · правильных: '+p.correct+' · ошибок: '+p.wrong+' · активных: '+p.errors.length+'</p><p>Данные хранятся отдельно в каждом браузере и на каждом устройстве.</p><button id=reset>Сбросить прогресс</button></article>';$('#reset').onclick=()=>{if(confirm('Сбросить прогресс?')){p={seen:[],correct:0,wrong:0,errors:[],history:[]};save();render('progress')}}}
fetch('bank.json').then(r=>r.json()).then(d=>{bank=d.questions;render('home')}).catch(()=>$('#app').innerHTML='<article class=card><h2>Не удалось загрузить bank.json</h2></article>');
